# Generated by Django 6.0 on 2026-01-05 00:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('studio', 'Studio'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('standalone', 'Standalone'), ('condo', 'Condo')], max_length=50)),
                ('location', models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('malindi', 'Malindi'), ('nyeri', 'Nyeri'), ('kisii', 'Kisii'), ('kitale', 'Kitale')], max_length=100)),
                ('specific_location', models.CharField(help_text='Specific area/estate', max_length=200)),
                ('host_name', models.CharField(max_length=100)),
                ('host_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'", regex='^\\+?1?\\d{9,15}$')])),
                ('host_whatsapp', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'", regex='^\\+?1?\\d{9,15}$')])),
                ('admin_contact', models.CharField(default='+254700000000', help_text='Default admin contact number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'", regex='^\\+?1?\\d{9,15}$')])),
                ('guests', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('beds', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to='listings/main/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='listings/extra/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='listings/extra/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='listings/extra/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
