# Generated by Django 6.0 on 2026-01-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Property Listing', 'verbose_name_plural': 'Property Listings'},
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_payment_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Featured Payment Amount'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('free', 'Free Listing'), ('featured', 'Featured Listing')], default='free', max_length=20, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
