# Generated by Django 6.0 on 2026-01-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('westlands', 'Westlands'), ('kilimani', 'Kilimani'), ('kileleshwa', 'Kileleshwa'), ('roysambu', 'Roysambu'), ('mirema', 'Mirema'), ('Trm drive', 'Trm drive'), ('Lumumba drive', 'Lumumba drive'), ('kahawa_sukari', 'Kahawa Sukari'), ('kahawa_wendani', 'Kahawa Wendani'), ('kasarani', 'Kasarani'), ('bypass', 'Bypass'), ('Membley', 'Membley'), ('ruiru', 'Ruiru'), ('zimmerman', 'Zimmerman'), ('pangani', 'Pangani'), ('ngara', 'Ngara'), ('gwakairu', 'Gwakairu'), ('kimbo', 'Kimbo'), ('k_road', 'K Road'), ('juja', 'Juja'), ('thika', 'Thika'), ('kahawa_west', 'Kahawa West'), ('kitengela', 'Kitengela'), ('kitisuru', 'Kitisuru'), ('komarock', 'Komarock'), ('lavington', 'Lavington'), ('loresho', 'Loresho'), ('ngong', 'Ngong'), ('rongai', 'Rongai'), ('embakasi', 'Embakasi'), ('fedha', 'Fedha'), ('south_b', 'South B'), ('south_c', 'South C'), ('kiambu', 'Kiambu'), ('thome', 'Thome'), ('kiambu_road', 'Kiambu Road'), ('utawala', 'Utawala'), ('eastleigh', 'Eastleigh'), ('donholm', 'Donholm'), ('mombasa', 'Mombasa'), ('eldoret', 'Eldoret'), ('nakuru', 'Nakuru'), ('naivasha', 'Naivasha'), ('nairobi-cbd', 'Nairobi cbd'), ('garden_city', 'Garden City'), ('homeland', 'Homeland'), ('hurlingham', 'Hurlingham'), ('kabete', 'Kabete'), ('kamulu', 'Kamulu'), ('kangemi', 'Kangemi'), ('karen', 'Karen'), ('kawangware', 'Kawangware'), ('milimani', 'Milimani'), ('muthaiga', 'Muthaiga'), ('mwiki', 'Mwiki'), ('nairobi_west', 'Nairobi West'), ('ongata_rongai', 'Ongata Rongai'), ('parklands', 'Parklands'), ('roasters', 'Roasters'), ('ruai', 'Ruai'), ('ruaka', 'Ruaka'), ('ruaraka', 'Ruaraka'), ('runda', 'Runda'), ('saika', 'Saika'), ('syokimau', 'Syokimau'), ('thogoto', 'Thogoto'), ('upper_hill', 'Upper Hill'), ('uthiru', 'Uthiru'), ('athiriver', 'Athiriver'), ('kisumu', 'Kisumu'), ('machakos', 'Machakos'), ('meru_town', 'Meru Town'), ('nanyuki', 'Nanyuki'), ('nyeri_town', 'Nyeri Town'), ('embu_town', 'Embu Town'), ('narok_town', 'Narok Town'), ('kisii_town', 'Kisii Town'), ('voi', 'Voi'), ('isiolo_town', 'Isiolo Town'), ('bomet', 'Bomet'), ('kakamega_town', 'Kakamega Town'), ('limuru', 'Limuru'), ('malindi', 'Malindi'), ('nyahururu', 'Nyahururu'), ('migori_town', 'Migori Town'), ('kitui_town', 'Kitui Town'), ('bungoma_town', 'Bungoma Town'), ('kilifi_town', 'Kilifi Town'), ('wangige', 'Wangige'), ('kericho_town', 'Kericho Town'), ('watamu', 'Watamu'), ('diani', 'Diani'), ('chuka', 'Chuka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('Own_compound', 'Own compound'), ('beach_house', 'beach house')], max_length=50),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
