# Generated by Django 6.0 on 2026-01-28 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_location_alter_listing_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='admin_contact',
            field=models.CharField(default='+254707341748', help_text='Default admin contact number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('westlands', 'Westlands'), ('kilimani', 'Kilimani'), ('kileleshwa', 'Kileleshwa'), ('roysambu', 'Roysambu'), ('mirema', 'Mirema'), ('Trm_drive', 'Trm drive'), ('Lumumba_drive', 'Lumumba drive'), ('kahawa_sukari', 'Kahawa Sukari'), ('kahawa_wendani', 'Kahawa Wendani'), ('kasarani', 'Kasarani'), ('bypass', 'Bypass'), ('Membley', 'Membley'), ('ruiru', 'Ruiru'), ('zimmerman', 'Zimmerman'), ('pangani', 'Pangani'), ('ngara', 'Ngara'), ('gwakairu', 'Gwakairu'), ('kimbo', 'Kimbo'), ('k_road', 'K Road'), ('juja', 'Juja'), ('thika', 'Thika'), ('kahawa_west', 'Kahawa West'), ('kitengela', 'Kitengela'), ('kitisuru', 'Kitisuru'), ('komarock', 'Komarock'), ('lavington', 'Lavington'), ('loresho', 'Loresho'), ('ngong', 'Ngong'), ('rongai', 'Rongai'), ('embakasi', 'Embakasi'), ('fedha', 'Fedha'), ('south_b', 'South B'), ('south_c', 'South C'), ('kiambu', 'Kiambu'), ('thome', 'Thome'), ('kiambu_road', 'Kiambu Road'), ('utawala', 'Utawala'), ('mombasa', 'Mombasa'), ('eldoret', 'Eldoret'), ('nakuru', 'Nakuru'), ('naivasha', 'Naivasha'), ('garden_city', 'Garden City'), ('homeland', 'Homeland'), ('hurlingham', 'Hurlingham'), ('kabete', 'Kabete'), ('kangemi', 'Kangemi'), ('karen', 'Karen'), ('kawangware', 'Kawangware'), ('milimani', 'Milimani'), ('muthaiga', 'Muthaiga'), ('mwiki', 'Mwiki'), ('nairobi_west', 'Nairobi West'), ('ongata_rongai', 'Ongata Rongai'), ('parklands', 'Parklands'), ('roasters', 'Roasters'), ('ruai', 'Ruai'), ('ruaka', 'Ruaka'), ('ruaraka', 'Ruaraka'), ('runda', 'Runda'), ('saika', 'Saika'), ('syokimau', 'Syokimau'), ('thogoto', 'Thogoto'), ('upper_hill', 'Upper Hill'), ('uthiru', 'Uthiru'), ('athiriver', 'Athiriver'), ('kisumu', 'Kisumu'), ('machakos', 'Machakos'), ('meru_town', 'Meru Town'), ('nanyuki', 'Nanyuki'), ('nyeri_town', 'Nyeri Town'), ('embu_town', 'Embu Town'), ('narok_town', 'Narok Town'), ('kisii_town', 'Kisii Town'), ('voi', 'Voi'), ('isiolo_town', 'Isiolo Town'), ('bomet', 'Bomet'), ('kakamega_town', 'Kakamega Town'), ('limuru', 'Limuru'), ('malindi', 'Malindi'), ('nyahururu', 'Nyahururu'), ('migori_town', 'Migori Town'), ('kitui_town', 'Kitui Town'), ('bungoma_town', 'Bungoma Town'), ('kilifi_town', 'Kilifi Town'), ('wangige', 'Wangige'), ('kericho_town', 'Kericho Town'), ('watamu', 'Watamu'), ('diani', 'Diani'), ('chuka', 'Chuka')], max_length=100),
        ),
    ]
